name: CI - ShadowOps Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: 📦 Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: ✅ Lint Python files
        run: |
          pip install flake8
          flake8 shadowops-bot/ --ignore=E501,W503

      - name: 🧪 Run ShadowOps Bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
        run: |
          python shadowops-bot/main.py
